"""Phase 1 - core organization/device structure

Creates: organizations, hospitals, departments, device_categories,
manufacturers, device_models, locations, devices.

This migration is hand-written (not autogenerated from any ORM) - the
database layer has no dependency on the backend. Every table, constraint,
and index below is explicit and reviewable.

Revision ID: 0001_phase1_core
Revises:
Create Date: 2026-09-16
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision = "0001_phase1_core"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- Shared trigger function: keeps updated_at correct no matter what
    # client touches the row (backend, admin tool, psql) - not something an
    # application layer can be trusted to always remember to set. ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # --- organizations ---------------------------------------------------
    op.create_table(
        "organizations",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("code", sa.String(50), nullable=False, unique=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.execute(
        "CREATE TRIGGER trg_organizations_updated_at BEFORE UPDATE ON organizations "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- hospitals ---------------------------------------------------------
    op.create_table(
        "hospitals",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("organization_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("code", sa.String(50), nullable=False),
        sa.Column("address", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("organization_id", "code", name="uq_hospital_org_code"),
    )
    op.execute(
        "CREATE TRIGGER trg_hospitals_updated_at BEFORE UPDATE ON hospitals "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- departments ---------------------------------------------------------
    op.create_table(
        "departments",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("hospital_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("hospital_id", "name", name="uq_department_hospital_name"),
    )
    op.execute(
        "CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- device_categories (added vs. your Phase-1 list, per the approved
    # ERD: device_models requires it) --------------------------------------
    op.create_table(
        "device_categories",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(100), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.execute(
        "CREATE TRIGGER trg_device_categories_updated_at BEFORE UPDATE ON device_categories "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- manufacturers ---------------------------------------------------------
    op.create_table(
        "manufacturers",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(255), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.execute(
        "CREATE TRIGGER trg_manufacturers_updated_at BEFORE UPDATE ON manufacturers "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- device_models ---------------------------------------------------------
    op.create_table(
        "device_models",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("manufacturer_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("device_category_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["manufacturer_id"], ["manufacturers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["device_category_id"], ["device_categories.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("manufacturer_id", "name", name="uq_device_model_manufacturer_name"),
    )
    op.create_index("ix_device_models_device_category_id", "device_models", ["device_category_id"])
    op.execute(
        "CREATE TRIGGER trg_device_models_updated_at BEFORE UPDATE ON device_models "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- locations ---------------------------------------------------------
    op.create_table(
        "locations",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("hospital_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("building", sa.String(100), nullable=True),
        sa.Column("floor", sa.String(50), nullable=True),
        sa.Column("room", sa.String(50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_locations_hospital_id", "locations", ["hospital_id"])
    op.execute(
        "CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )

    # --- devices -------------------------------------------------------------
    # NOTE: these ENUM objects create their Postgres type automatically the
    # first time they're used in a table (via op.create_table below) - no
    # separate CREATE TYPE call needed, and no double-create risk.
    device_status = pg.ENUM(
        "active", "under_maintenance", "out_of_service", "decommissioned",
        name="device_status",
    )
    device_criticality = pg.ENUM(
        "low", "medium", "high", "critical",
        name="device_criticality",
    )

    op.create_table(
        "devices",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("organization_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("hospital_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("department_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("location_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("device_model_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("device_code", sa.String(50), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("serial_number", sa.String(255), nullable=True),
        sa.Column("qr_identifier", sa.String(255), nullable=False, unique=True),
        sa.Column("status", device_status, nullable=False, server_default="active"),
        sa.Column("criticality", device_criticality, nullable=False, server_default="medium"),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("warranty_expiry", sa.Date(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["device_model_id"], ["device_models.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("hospital_id", "device_code", name="uq_device_hospital_code"),
        sa.CheckConstraint(
            "warranty_expiry IS NULL OR installation_date IS NULL OR warranty_expiry >= installation_date",
            name="ck_device_warranty_after_installation",
        ),
    )
    op.create_index("ix_devices_organization_id", "devices", ["organization_id"])
    op.create_index("ix_devices_department_id", "devices", ["department_id"])
    op.create_index("ix_devices_location_id", "devices", ["location_id"])
    op.create_index("ix_devices_device_model_id", "devices", ["device_model_id"])
    op.create_index("ix_devices_serial_number", "devices", ["serial_number"])
    op.execute(
        "CREATE TRIGGER trg_devices_updated_at BEFORE UPDATE ON devices "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    op.drop_table("devices")
    op.execute("DROP TYPE IF EXISTS device_criticality;")
    op.execute("DROP TYPE IF EXISTS device_status;")
    op.drop_table("locations")
    op.drop_table("device_models")
    op.drop_table("manufacturers")
    op.drop_table("device_categories")
    op.drop_table("departments")
    op.drop_table("hospitals")
    op.drop_table("organizations")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
